import {
  AlignJustify,
  Facebook,
  Globe,
  Instagram,
  Loader2,
  MessageCircle,
  ChevronDownSquare,
  PlusCircle,
  X,
  Globe2,
  CornerUpLeft,
  BookCopy,
  Store,
  Calendar,
  CalendarDays,
  Trash2,
  CircleDollarSign,
  Calculator,
  ChevronDown,
  ChevronRight,
  FileSearch,
  Coins,
  Send,
  Truck,
  Tag,
  Search,
  XCircle,
  MailCheck,
  BellOff,
} from "lucide-react";

export const Icons = {
  Loader: Loader2,
  Text: AlignJustify,
  Facebook,
  Instagram,
  Message: MessageCircle,
  Web: Globe,
  ChevronSquareDown: ChevronDownSquare,
  Add: PlusCircle,
  Cancel: X,
  Globe: Globe2,
  CornerUpLeftArrow: CornerUpLeft,
  Category: BookCopy,
  Store,
  Calendar,
  CalendarDays,
  Delete: Trash2,
  Money: CircleDollarSign,
  Calculator,
  ChevronDown,
  ChevronRight,
  View: FileSearch,
  Coins,
  Send,
  Courier: Truck,
  Tag,
  Search,
  CancelCircle: XCircle,
  Delivered: MailCheck,
  NoDelivery: BellOff,
};

export default Icons;
